apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjoKCXsKCQkiZ2hjci5pbyI6CgkJewoJCQkJImF1dGgiOiAiYTNWNmJtVmphR1ZyT21kcGRHaDFZbDl3WVhSZk1URkJUMWRPUWtOUk1EaEJOMjFrVTBKdGJtcDNUVjlzYWpoV2NYaElRbms0U2xadWNHcG5aMmM1VDFobWVVMHlSbG95WTIxMlNGTlJZVVpsVWt4NFEwNXpOMGRSTmtKRVNFVXhVMDFWVm1Sdk9BPT0iCgoJCX0KCX0sCgoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
